### ISSUE TITLE
How to set a default after the fact

### ISSUE THREAD

**Issue by ronkorving** [mozilla/node-convict#291]
I have a project where I put a lot of overridable values into convinct, and a common use-case I encounter is that I want to set default values *late*.

Example:

schema.yml:

```yaml
organization:
  name:
      doc: Name of the organization
      format: String
      default: null
      arg: organization-name
domainName:
  doc: The domain name to be registered for the website
  format: String
  default: null
  arg: domain-name
```

I would like the domain name to default to `${organization.name}.awesomewebsites.com`. The organization-name is not optional; it has to be provided. But the domain-name can be easily derived, yet has a very obvious default based on the organization-name.

How can I achieve this with convict? Assuming this is currently impossible, I can see 2 theoretical solutions:

## Via templates

schema.yml:

```yaml
organization:
  name:
      doc: Name of the organization
      format: String
      default: null
      arg: organization-name
domainName:
  doc: The domain name to be registered for the website
  format: String
  default: '${organization.name}.awesomewebsites.com'   // convict will resolve this late, when the default is first needed
  arg: domain-name
```

## Via a default-function

schema.js:

```js
module.exports = {
  organization: {
    name: {
      doc: 'Name of the organization',
      format: String,
      default: null,
      arg: 'organization-name'
    }
  },
  domainName: {
    doc: 'The domain name to be registered for the website',
    format: String
    default: (config) => {
      return config.get('organization.name') + '.awesomewebsites.com';
    },
    arg: 'domain-name'
  }
};
```

## Via API

```
const config = convict(mySchema);
config.loadFile('config.yml');
config.setDefault('domainName', config.get('organization.name') + '.awesomewebsites.com');
```

I would love to hear what y'all think about feasibility and if there's any preference wrt. the solutions. Thanks!
