### ISSUE TITLE
Add regex at name for addFormat ?

### ISSUE THREAD

**Issue by A-312** [mozilla/node-convict#312]
Can I add a regex system for the name property ? Like this:

```js
convict.addFormat({
  name: /^array\[.*\]$/,
  // ...
})
```

After my change, name will accept `str` and `regex`.

Usage:

```yml
path:
  routes: 
    # path.routes
    format: array[String]
    default: ["app/config/routes.yml"]

number:
  # number
  default: [1, 4, 5]
  format: array[int]
```
