### ISSUE TITLE
Select keyName with regex in schema for children object

### ISSUE THREAD

**Issue by A-312** [mozilla/node-convict#325]
I need to check several children object with the same schema but an unknow keyName.

The most obvious example is an object "hands" with left and right subkey/subobject. I proprose to add regex Filter.

Schema : 

```yml
hands:
  # hands
  Filter:RegExp(/(left|right)/):
  # hands.left or hands.right
    fingers:
    # hands.xxx.fingers
      index:
      # hands.xxx.fingers.index
        format: String
      middle:
       # hands.xxx.fingers.middle
        format: String
      ring:
      # hands.xxx.fingers.ring
        format: String
      little:
      # hands.xxx.fingers.little
        format: String
      thumb:
      # hands.xxx.fingers.thumb
        format: String
```

Config : 

```yml
hands:
  left:
    fingers:
      # ...
  right:
    fingers:
      # ...
```

# Other solution : 

## Filter with function instead of RegExp :

Schema : 

```yml
hands:
  # hands
  Filter:Function(regexLeftorRight):
  # hands.left or hands.right
```

Javascript : 

```js
convict.addKeyFilter("regexLeftorRight", (a) => /(left|right)/.test(a))
```

Or we can add the twice (`Filter:RegExp(xxxxx)` and `Filter:Function(xxxxxxxxxxx)`).
